# Intro to Numpy

In [1]:
import numpy as np

In [2]:
lst = (1,2,3,5,6)

In [3]:
type(lst)

tuple

In [4]:
arr = np.array((1,2,3))

In [5]:
arr

array([1, 2, 3])

In [6]:
np.sort(arr)[::-1]     #desending order

array([3, 2, 1])

In [7]:
np.flipud(arr)        #reverse the array

array([3, 2, 1])

In [8]:
arr.transpose()

array([1, 2, 3])

In [9]:
arr = np.array(lst)

In [10]:
arr

array([1, 2, 3, 5, 6])

In [11]:
type(arr)

numpy.ndarray

In [12]:
arr.ndim

1

In [13]:
lst = [[1,2,3],
      [4,5,6],
      [7,8,9]]

In [14]:
arr = np.array(lst)

In [15]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr[1:1]

array([], dtype=int32)

In [12]:
arr.ndim

2

In [13]:
arr.shape

(3, 3)

In [14]:
arr.size

9

In [17]:
arr.dtype

dtype('int32')

In [16]:
zeros = np.zeros((3,5))

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
ones = np.ones((6,2))

In [19]:
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
# numpy.zeros method
 
import numpy as geek
 
b = geek.zeros(2, dtype = int)
print("Matrix b : \n", b)
 
a = geek.zeros([2, 2], dtype = int)
print("\nMatrix a : \n", a)
 
c = geek.zeros([3, 3])
print("\nMatrix c : \n", c)


Matrix b : 
 [0 0]

Matrix a : 
 [[0 0]
 [0 0]]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
#The numpy.ones() function returns a new array of given shape and type, with ones.
#Syntax: numpy.ones(shape, dtype = None, order = 'C') 

# Python Program illustrating
# numpy.ones method
 
import numpy as geek
 
b = geek.ones(2, dtype = int)
print("Matrix b : \n", b)
 
a = geek.ones([2, 2], dtype = int)
print("\nMatrix a : \n", a)
 
c = geek.ones([3, 3])
print("\nMatrix c : \n", c)


Matrix b : 
 [1 1]

Matrix a : 
 [[1 1]
 [1 1]]

Matrix c : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# Generate the random number and reshape

In [3]:
# Python program explaining
# numpy.random.random() function
  
# importing numpy
import numpy as geek
  
  
# output array
out_arr = geek.random.random(3)
print ("Output 1D Array filled with random floats : ", out_arr) 


Output 1D Array filled with random floats :  [0.39914368 0.46430207 0.75530385]


In [24]:
#arange([start,] stop[, step,][, dtype])
#Array of evenly spaced values.
#Length of array being generated  = Ceil((Stop - Start) / Step)
# numpy.arange method
import numpy as geek
 
print("A\n", geek.arange(4).reshape(2, 2), "\n")
print("A\n", geek.arange(4, 10), "\n")
print("A\n", geek.arange(4, 20, 3), "\n")
# numpy arange method
 
import numpy as geek
 
print("A\n", geek.arange(4).reshape(2, 2), "\n")
print("A\n", geek.arange(4, 10), "\n")
print("A\n", geek.arange(4, 20, 3), "\n")

A
 [[0 1]
 [2 3]] 

A
 [4 5 6 7 8 9] 

A
 [ 4  7 10 13 16 19] 



In [25]:
#The numpy.linspace() function returns number spaces evenly w.r.t interval
""""numpy.linspace(start,
               stop,
               num = 50,
               endpoint = True,
               retstep = False,
               dtype = None)"""
# numpy.linspace method
 
import numpy as geek
 
# restep set to True
print("B\n", geek.linspace(2.0, 3.0, num=5, retstep=True), "\n")
 
# To evaluate sin() in long range
x = geek.linspace(0, 2, 10)
print("A\n", geek.sin(x))

B
 (array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25) 

A
 [0.         0.22039774 0.42995636 0.6183698  0.77637192 0.8961922
 0.9719379  0.99988386 0.9786557  0.90929743]


In [26]:
#The numpy.reshape() function shapes an array without changing the data of the array.
#numpy.reshape(array, shape, order = 'C')

# numpy.reshape() method
 
import numpy as geek
 
# array = geek.arrange(8)
# The 'numpy' module has no attribute 'arrange'
array1 = geek.arange(8)
print("Original array : \n", array1)
 
# shape array with 2 rows and 4 columns
array2 = geek.arange(8).reshape(2, 4)
print("\narray reshaped with 2 rows and 4 columns : \n",
      array2)
 
# shape array with 4 rows and 2 columns
array3 = geek.arange(8).reshape(4, 2)
print("\narray reshaped with 4 rows and 2 columns : \n",
      array3)
 
# Constructs 3D array
array4 = geek.arange(8).reshape(2, 2, 2)
print("\nOriginal array reshaped to 3D : \n",
      array4)

Original array : 
 [0 1 2 3 4 5 6 7]

array reshaped with 2 rows and 4 columns : 
 [[0 1 2 3]
 [4 5 6 7]]

array reshaped with 4 rows and 2 columns : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

Original array reshaped to 3D : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [27]:
np.random.random((3,3))

array([[0.29666658, 0.55611   , 0.06041318],
       [0.50392494, 0.73516164, 0.18906369],
       [0.46582396, 0.61644563, 0.23500887]])

In [28]:
if np.random.random() > 0.5:
    print("function run")
else:
    print("function not run")

function run


In [29]:
np.arange(1,10,3)

array([1, 4, 7])

In [30]:
arr = np.random.random((4,3))

In [31]:
arr

array([[0.19368387, 0.71482291, 0.1981047 ],
       [0.92123595, 0.06680662, 0.41740583],
       [0.31917637, 0.20188622, 0.1688977 ],
       [0.44079616, 0.4993019 , 0.76639711]])

In [32]:
arr = np.reshape(arr,(3,4))

In [33]:
arr

array([[0.19368387, 0.71482291, 0.1981047 , 0.92123595],
       [0.06680662, 0.41740583, 0.31917637, 0.20188622],
       [0.1688977 , 0.44079616, 0.4993019 , 0.76639711]])

In [34]:
arr.flatten()

array([0.19368387, 0.71482291, 0.1981047 , 0.92123595, 0.06680662,
       0.41740583, 0.31917637, 0.20188622, 0.1688977 , 0.44079616,
       0.4993019 , 0.76639711])

# Arithmatic operation on Array

# Addition

In [1]:
import numpy as np
 
# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
 
# Performing addition using arithmetic operator
add_ans = a+b
print(add_ans)
 
# Performing addition using numpy function
add_ans = np.add(a, b)
print(add_ans)
 
# The same functions and operations can be used for multiple matrices
c = np.array([1, 2, 3, 4])
add_ans = a+b+c
print(add_ans)
 
add_ans = np.add(a, b, c)
print(add_ans)

[  7  77  23 130]
[  7  77  23 130]
[  8  79  26 134]
[  7  77  23 130]


# Substraction

In [2]:
import numpy as np
 
# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
 
# Performing subtraction using arithmetic operator
sub_ans = a-b
print(sub_ans)
 
# Performing subtraction using numpy function
sub_ans = np.subtract(a, b)
print(sub_ans)

[ 3 67  3 70]
[ 3 67  3 70]


# Multiplication

In [55]:
import numpy as np
 
# Defining both the matrices
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
 
c = np.stack([a,b], axis = 1)
print(c)
# Performing multiplication using arithmetic operator
#mul_ans = a*b
#print(mul_ans)
 
# Performing multiplication using numpy function
#mul_ans = np.multiply(a, b)
#mul_ans = a.dot(b)
#print(mul_ans)
#np.concatenate((a,b.T),axis = 1)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [56]:
import numpy as np
 
# Defining both the matrices
a = np.array([[1,2,3,4],[5,6,7]])
b = np.array([[5,6],[7,8]])
 
a = np.column_stack([a,b])
print(a)

[[list([1, 2, 3, 4]) 5 6]
 [list([5, 6, 7]) 7 8]]


C:\Users\91955\AppData\Local\Temp\ipykernel_23468\2310689439.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([[1,2,3,4],[5,6,7]])


# Division

In [4]:
import numpy as np
 
# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
 
# Performing division using arithmetic operators
div_ans = a/b
print(div_ans)
 
# Performing division using numpy functions
div_ans = np.divide(a, b)
print(div_ans)

[ 2.5        14.4         1.3         3.33333333]
[ 2.5        14.4         1.3         3.33333333]


In [35]:
arr1 = np.array([1,2,3,4,5])

In [20]:
arr1

array([1, 2, 3, 4, 5])

In [21]:
print(arr1 + 1)
print(arr1 -1)
print(arr1 * 5)
print(arr1 / 2)
print(arr1 ** 2)

[2 3 4 5 6]
[0 1 2 3 4]
[ 5 10 15 20 25]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]


In [22]:
arr1 += 1

In [23]:
arr1.min()

2

In [24]:
arr1.max()

6

In [7]:
import numpy
 
# creating a two dimensional
# numpy array of integers
arr = numpy.array([[11, 2, 3],
                     [4, 5, 16],
                      [7, 81, 22]])
 
# finding the maximum and
# minimum element in the array
max_element_column = numpy.max(arr, 0)
max_element_row = numpy.max(arr, 1)
 
min_element_column = numpy.amin(arr, 0)
min_element_row = numpy.amin(arr, 1)
 
# printing the result
print('maximum elements in the columns of the array is:',
      max_element_column)
 
print('maximum elements in the rows of the array is:',
      max_element_row)
 
print('minimum elements in the columns of the array is:',
      min_element_column)
 
print('minimum elements in the rows of the array is:',
      min_element_row)

maximum elements in the columns of the array is: [11 81 22]
maximum elements in the rows of the array is: [11 16 81]
minimum elements in the columns of the array is: [4 2 3]
minimum elements in the rows of the array is: [2 4 7]


In [25]:
arr1.min()

2

In [26]:
arr.max(axis = 0)

6

In [36]:
arr2 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr3 = np.array([[9,8,7],
                [6,5,4],
                [3,2,1]])

In [37]:
arr2 + arr3

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [38]:
arr2 * arr3

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [39]:
arr2.dot(arr3)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [40]:
(1*9) + (2*6) +(3*3)

30

In [41]:
arr2.dot(arr3)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [42]:
arr3

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [44]:
arr3.dot(arr2)

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])

In [47]:
arr2[:]  

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
arr2[1:2,1:2]   #to get single element from list

array([[5]])

In [53]:
arr2[2:-2]

array([], shape=(0, 3), dtype=int32)

# Array sorting

In [54]:
import numpy as np
 
# sort along the first axis
a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = 0)       
print ("Along first axis : \n", arr1)       
 
 
# sort along the last axis
a = np.array([[10, 15], [12, 1]])
arr2 = np.sort(a, axis = -1)       
print ("\nAlong first axis : \n", arr2)
 
 
a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = None)       
print ("\nAlong none axis : \n", arr1)

Along first axis : 
 [[10  1]
 [12 15]]

Along first axis : 
 [[10 15]
 [ 1 12]]

Along none axis : 
 [ 1 10 12 15]


# Type of sorting

In [55]:
arr = np.array([[7,3,8,6,4], [7,2,9,8,6],[5,4,2,3,1]])
print(np.sort(arr , axis = 0, kind = 'mergesort'))
print()
print(np.sort(arr , axis = 1, kind = 'quicksort'))
print()
print(np.sort(arr , kind = 'heapsort'))

[[5 2 2 3 1]
 [7 3 8 6 4]
 [7 4 9 8 6]]

[[3 4 6 7 8]
 [2 6 7 8 9]
 [1 2 3 4 5]]

[[3 4 6 7 8]
 [2 6 7 8 9]
 [1 2 3 4 5]]


# Array merging 

In [56]:
# vstack() function
  
import numpy as geek
  
# input array
in_arr1 = geek.array([ 1, 2, 3] )
print ("1st Input array : \n", in_arr1) 
  
in_arr2 = geek.array([ 4, 5, 6] )
print ("2nd Input array : \n", in_arr2) 
  
# Stacking the two arrays vertically
out_arr = geek.vstack((in_arr1, in_arr2))
print ("Output vertically stacked array:\n ", out_arr)

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output vertically stacked array:
  [[1 2 3]
 [4 5 6]]


In [57]:
# vstack() function
  
import numpy as geek
  
# input array
in_arr1 = geek.array([[ 1, 2, 3], [ -1, -2, -3]] )
print ("1st Input array : \n", in_arr1) 
  
in_arr2 = geek.array([[ 4, 5, 6], [ -4, -5, -6]] )
print ("2nd Input array : \n", in_arr2) 
  
# Stacking the two arrays vertically
out_arr = geek.vstack((in_arr1, in_arr2))
print ("Output stacked array :\n ", out_arr)

1st Input array : 
 [[ 1  2  3]
 [-1 -2 -3]]
2nd Input array : 
 [[ 4  5  6]
 [-4 -5 -6]]
Output stacked array :
  [[ 1  2  3]
 [-1 -2 -3]
 [ 4  5  6]
 [-4 -5 -6]]


In [58]:
# hstack() function
  
import numpy as geek
  
# input array
in_arr1 = geek.array([ 1, 2, 3] )
print ("1st Input array : \n", in_arr1) 
  
in_arr2 = geek.array([ 4, 5, 6] )
print ("2nd Input array : \n", in_arr2) 
  
# Stacking the two arrays horizontally
out_arr = geek.hstack((in_arr1, in_arr2))
print ("Output horizontally stacked array:\n ", out_arr)

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output horizontally stacked array:
  [1 2 3 4 5 6]


In [59]:
# hstack() function
  
import numpy as geek
  
# input array
in_arr1 = geek.array([[ 1, 2, 3], [ -1, -2, -3]] )
print ("1st Input array : \n", in_arr1) 
  
in_arr2 = geek.array([[ 4, 5, 6], [ -4, -5, -6]] )
print ("2nd Input array : \n", in_arr2) 
  
# Stacking the two arrays horizontally
out_arr = geek.hstack((in_arr1, in_arr2))
print ("Output stacked array :\n ", out_arr)

1st Input array : 
 [[ 1  2  3]
 [-1 -2 -3]]
2nd Input array : 
 [[ 4  5  6]
 [-4 -5 -6]]
Output stacked array :
  [[ 1  2  3  4  5  6]
 [-1 -2 -3 -4 -5 -6]]


In [60]:
# numpy.concatenate() function
  
# importing numpy as geek 
import numpy as geek
  
arr1 = geek.array([[2, 4], [6, 8]])
arr2 = geek.array([[3, 5], [7, 9]])
  
gfg = geek.concatenate((arr1, arr2), axis = 0)
  
print (gfg)

[[2 4]
 [6 8]
 [3 5]
 [7 9]]


In [61]:
# Python program explaining
# numpy.vsplit() function
  
# importing numpy as geek 
import numpy as geek
  
arr = geek.arange(9.0).reshape(3, 3)
  
gfg = geek.vsplit(arr, 1)
  
print (gfg)

[array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])]


In [62]:
# numpy.hsplit() function
  
# importing numpy as geek 
import numpy as geek
  
arr = geek.arange(16.0).reshape(4, 4)
  
gfg = geek.hsplit(arr, 2)
  
print (gfg)

[array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])]


# Array slicing

In [63]:
#Array[ Initial : End : IndexJump ]
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
arr[3: ]

array([4, 5, 6, 7, 8])

In [64]:
print(arr[ : -3])
print(arr[3  :  -3])

[1 2 3 4 5]
[4 5]


In [65]:
arr = np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [66]:
print(arr[ 3 , 1])
print()
print(arr[ 1: , 1:])

3

[[6 7 8]
 [7 6 5]
 [3 2 1]]


# Automating using numpy

In [85]:
import numpy as np

In [86]:
arr = np.array([1,2,3,4])

In [87]:
arr

array([1, 2, 3, 4])

In [88]:
arr[0]

1

In [89]:
arr[3: ]

array([4])

In [90]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [91]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
arr [:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
arr[:1,:]

array([[1, 2, 3]])

In [94]:
arr[2,:]

array([7, 8, 9])

In [95]:
arr[1:,1:2]

array([[5],
       [8]])

In [67]:
lst = [1,2,3,4,5,6,7,8,9,10]
for i in lst:
  if (i > 5):
    print(i)

6
7
8
9
10


In [68]:
lst = np.array([1,2,3,4,5,6,7,8,9,10])
print(lst[lst>5]) #in a single line we have done the same thing which we did previously and this time without using the for loop

[ 6  7  8  9 10]


In [69]:
import numpy as np

In [70]:
lst = [1,2,3,4,5]

In [100]:
q =0
for i in lst:
    if(i>2):
        print(i)
        q += 1
print(q)

3
4
2


In [96]:
q = 0

for i in lst:
  if (i > 5):
    print(i)
    q += 1

print(q)
     
    

0


In [101]:
print(len(lst[lst > 5]))
print(lst[lst>5])
     

0
[]


In [77]:
lst = np.array([1,2,3,4])

In [78]:
lst

array([1, 2, 3, 4])

In [79]:
lst >5

array([False, False, False, False])

In [80]:
lst[lst>5]

array([], dtype=int32)

In [81]:
len(lst[lst > 5])

0

In [83]:
print(lst % 3 == 0 )

[False False  True False]


In [84]:
print(lst[lst % 3 == 0])

[3]


In [70]:
arr33 = [1,2,3,4,5,6,7]
print(arr33[2:-3])

[3, 4]


# os --Reading Material 

In [ ]:
OS command for windows

In [ ]:
1.      dir: works same as ls shows the content of cwd

2.      cd: used to change the directory.

3.      cls: to clear the command prompt.

4.      mkdir filename: to create a directory.

5.      rmdir filename: to remove the directory.

6.      date: To get the current date and time.

7.      copy filename destination: used to copy the file and paste in the destination directory.

8.      move filename destination: used to move the file and paste it in the destination directory.

9.      rename old_filename new_filename: used to rename a file

Example rename Hello.txt World.txt will rename the Hello.txt file to World.txt.

10.   exit: to close the command prompt.

In [ ]:
                                               OS Basics  

import os : used to import the os library

os.getcwd : used to get the current working directory(cwd).

os.chdir(“directory_name”) : To go inside a folder.

os.chdir(“..”) : To go back to the previous directory.

os.mkdir(“file_name”) : To create a directory in the cwd.

os.mkdirs(“filename/filename1/filename2”): Used to create directories within directories.

os.remove(“File_Name”): can be used to remove a folder but if folder is empty if it contains anything it can’t be used.

os.rmdir(“parent_name/sub_directory_name”):

Example os.rmdir(“Test/Test1”) then os.rmdir(“Test”)

os.rename(‘old_file_name’,’new_file_name’) : used to rename a file

os.getsize(“folder_name”) : gives size of folder in kbs.

In [ ]:
To see all the sub-directories contained in a directory

Let’s say we have a folder Imgs and want to check all the sub-directories contained in the directory Imgs
we can automate this by:

for i in os.listdir('Imgs'):

    if i != '.DS_Store':  ##System

        print(i)

This code can be used to print all the sub-directories present inside the directory Imgs.

In [ ]:
os.path.exists(“path”): Example os.path.exists(“Imgs/Test1”) this will return a Boolean result

In [2]:
import os

In [3]:
if os.path.exists("Imgs/G"):
    print("Folder Already Exists!")
else:
    os.mkdir('Imgs/G')

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'Imgs/G'

In [ ]:
                     #Creating Sub Directories in Bulk:
n = 'GFG'
os.mkdir(n)
for i in range(1000):
    name = n +'/'+ n + " " + str(i+1) //i=0 GFG/GFG1 
                                     // i=50 GFG/GFG50
    os.mkdir(name)

In [ ]:
           #Hierarchal Bulk Directory Creation:

master = 'GFG'
os.mkdir(master)
n = 5
m = 5
for i in range(n):
    name = master +'/'+ master + " " + str(i+1)
    os.mkdir(name) 
    for j in range(m):
        name = master +'/'+ master + " " + str(i+1) +"/"+ master + " " + str(j+1) 
        os.mkdir(name)        
print(n*m + n + 1)

In [ ]:
                                  #reading txt fle in bulk
for i in files:
    if i != '.DS_Store':
        fd = open('Files/'+i,'r')
        print('Files/'+i, fd.read())
        fd.close()